[package]
name = "threshold"
version = "0.1.0"
authors = ["nikkolasg"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.5.1"
rand = "0.7"
smallbitvec = "2.4.0"

# for ECIES
chacha20poly1305 = "0.3"
hkdf = "0.8"
sha2 = "0.8"


# bls12_381
paired = { version = "0.18.0", optional = true }
ff = { version = "0.2", package = "fff", optional = true }
groupy = {version = "0.3.0", optional = true }


#algebra_core = { git = "https://github.com/scipr-lab/zexe" }

[features]
default = [ "bls12_381"]
bls12_381 = ["paired", "groupy", "ff"]
